/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author dhadotid
 */
public class JFAdminRecipeDetail extends javax.swing.JFrame {
    double qty1 = 0;
    double has = 0;
    double Harga = 0;
    String qty = "";
    String expdate = "";
    /**
     * Creates new form JFAdminRecipeDetail
     */
    public JFAdminRecipeDetail() {
        super("Recipe");
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        setResizable(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        txtIDR.setEnabled(false);
        btnUpdate.setEnabled(false);
        txtIDRD.setEnabled(false);
        txtSub.setEnabled(false);
        tableload();
        txtIDD.setEnabled(false);
        tableloaddrug();
        autoidrecipe();
        autoid();
        txtQty.setText("0");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIDRD = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecipeDetail = new javax.swing.JTable();
        txtIDR = new javax.swing.JTextField();
        cdSearch = new javax.swing.JComboBox();
        txtIDD = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        lblRecipeDetail = new javax.swing.JLabel();
        txtSub = new javax.swing.JTextField();
        lblIDRD = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();
        lblIDR = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        lblIDD = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        lblQty = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        lblDose = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        lblSub = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        txtDose = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbDrug = new javax.swing.JComboBox();
        txtSearchDrug = new javax.swing.JTextField();
        btnSearchDrug = new javax.swing.JButton();
        btnRefreshDrug = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDrug = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtIDRD.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N

        tblRecipeDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Recipe Detail", "ID Recipe", "ID Drug", "Qty", "Dose", "Subtotal"
            }
        ));
        tblRecipeDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRecipeDetailMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRecipeDetail);

        txtIDR.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N

        cdSearch.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        cdSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID Recipe", "ID Drug" }));

        txtIDD.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N

        txtQty.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        txtQty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQtyFocusLost(evt);
            }
        });
        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });

        lblRecipeDetail.setFont(new java.awt.Font("Californian FB", 1, 36)); // NOI18N
        lblRecipeDetail.setText("Recipe");

        txtSub.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N

        lblIDRD.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        lblIDRD.setText("ID Recipe Detail");

        btnInsert.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        lblIDR.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        lblIDR.setText("ID Recipe");

        btnUpdate.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblIDD.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        lblIDD.setText("ID Drug");

        lblSearch.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        lblSearch.setText("Search Recipe");

        lblQty.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        lblQty.setText("Qty");

        txtSearch.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N

        lblDose.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        lblDose.setText("Dose");

        btnSearch.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblSub.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        lblSub.setText("Subtotal");

        btnRefresh.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        txtDose.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel1.setText("Search Drug");

        cbDrug.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        cbDrug.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DrugName", "ID Drug" }));

        txtSearchDrug.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N

        btnSearchDrug.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        btnSearchDrug.setText("Search");
        btnSearchDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDrugActionPerformed(evt);
            }
        });

        btnRefreshDrug.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        btnRefreshDrug.setText("Refresh");
        btnRefreshDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshDrugActionPerformed(evt);
            }
        });

        tbDrug.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDrug.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDrugMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbDrug);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRecipeDetail, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIDRD)
                                    .addComponent(lblIDD)
                                    .addComponent(lblIDR)
                                    .addComponent(lblQty)
                                    .addComponent(lblDose))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtIDRD)
                                            .addComponent(txtIDR)
                                            .addComponent(txtIDD)
                                            .addComponent(txtQty)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDose))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblSub)
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnInsert, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnUpdate))
                                    .addComponent(txtSub))))
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefresh))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbDrug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearchDrug, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearchDrug)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRefreshDrug)))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblRecipeDetail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIDRD)
                            .addComponent(txtIDRD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIDR)
                            .addComponent(txtIDR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIDD)
                            .addComponent(txtIDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSearch)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch)
                            .addComponent(btnRefresh)
                            .addComponent(cdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQty)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cbDrug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchDrug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchDrug)
                    .addComponent(btnRefreshDrug))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDose)
                            .addComponent(txtDose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSub)
                            .addComponent(txtSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnInsert, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        double qty1 = 0;
        double has = 0;
        qty1 = Double.parseDouble(txtQty.getText());
        has = qty1 * Harga;
        String fixhasil = "";
        txtSub.setText(fixhasil);
    }//GEN-LAST:event_txtQtyActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        //Update
        PreparedStatement ps;
        try {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure want to Update?" + txtIDR.getText(), "Update", dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
                if(txtIDR.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Id Recipe is incorret");
                }else if(txtIDD.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Id Drug is incorret, please select id drug from table drug");
                }else if(txtQty.getText().equals("") || txtQty.getText().equals("0") || txtQty.getText().matches("^\\d+$") == false){
                    JOptionPane.showMessageDialog(null, "Please enter the Quantity or qty invalid format");
                }else if(txtDose.getText().matches("^[0-9]{1,1}[X,x][0-9]{1,1}$") == false || txtDose.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Please enter dose drug");
                }else{
                    if(txtIDR.getText().equals("full")){
                        JOptionPane.showConfirmDialog(null, "Data Recipe has been full");
                    }else{
                        
                        int i = 0;
                        if(i != 0){
                            JOptionPane.showMessageDialog(null, "Data Recipe successful updated");
                            tableload();
                            clearall();
                            autoid();
                            autoidrecipe();
                        }else{
                            JOptionPane.showMessageDialog(null, "Data Recipe failed updated");
                        }
                    }
                }
            }

        } catch (Exception ex) {
            System.out.println("Error: " + ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        //Refresh
        clearall();
        autoid();
        tableload();
        autoidrecipe();
        tableloaddrug();
        btnInsert.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        //Insert
        PreparedStatement ps;
        try {
            if(txtIDR.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Please select id recipe from table");
            }else if(txtIDD.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Id Drug is incorret, please select id drug from the table drug");
            }else if(txtQty.getText().equals("") || txtQty.getText().equals("0") || txtQty.getText().matches("^\\d+$") == false){
                JOptionPane.showMessageDialog(null, "Please enter the Quantity or qty invalid format");
            }else if(txtDose.getText().matches("^[0-9]{1,1}[X,x][0-9]{1,1}$") == false || txtDose.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Please enter dose drug");
            }else{
                if(txtIDR.getText().equals("full")){
                    JOptionPane.showConfirmDialog(null, "Data Recipe has been full");
                }else{
                    
                    int i = 0;
                    if(i != 0){
                        JOptionPane.showMessageDialog(null, "Data Recipe successful inputted");
                        autoid();
                        tableload();
                        txtIDR.setText("");
                        txtIDD.setText("");
                        txtQty.setText("0");
                        txtDose.setText("");
                        txtSub.setText("");
                        autoidrecipe();
                    }else{
                        JOptionPane.showMessageDialog(null, "Data Recipe failed inputted");
                    }
                }
            }
        } catch (Exception ex) {
            System.out.println("Error: " + ex);
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void tblRecipeDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRecipeDetailMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblRecipeDetail.getModel();
        int selectedRowIndex = tblRecipeDetail.getSelectedRow();
        
        txtIDRD.setText(model.getValueAt(selectedRowIndex, 0).toString());
        txtIDR.setText(model.getValueAt(selectedRowIndex, 1).toString());
        txtIDD.setText(model.getValueAt(selectedRowIndex, 2).toString());
        txtQty.setText((model.getValueAt(selectedRowIndex, 3).toString()));
        txtDose.setText((model.getValueAt(selectedRowIndex, 4).toString()));
        txtSub.setText((model.getValueAt(selectedRowIndex, 5).toString()));
        
        btnUpdate.setEnabled(true);
        btnInsert.setEnabled(false);
    }//GEN-LAST:event_tblRecipeDetailMouseClicked

    private void tbDrugMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDrugMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tbDrug.getModel();
        int selectedRowIndex = tbDrug.getSelectedRow();
        
        txtIDD.setText(model.getValueAt(selectedRowIndex, 0).toString());
        String hargastr;
        hargastr = (model.getValueAt(selectedRowIndex, 5).toString());
        Harga = Double.parseDouble(hargastr);
        qty = (model.getValueAt(selectedRowIndex, 3).toString());
        expdate = (model.getValueAt(selectedRowIndex, 4).toString());
    }//GEN-LAST:event_tbDrugMouseClicked

    private void txtQtyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQtyFocusLost
        // TODO add your handling code here:
        //calculate
        String qs = "";
        qs = txtQty.getText();
        qty1 = Double.parseDouble(qs);
        has = qty1 * Harga;
        String fixhasil = "";
        fixhasil = String.valueOf(has);
        txtSub.setText(fixhasil);
    }//GEN-LAST:event_txtQtyFocusLost

    private void btnRefreshDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshDrugActionPerformed
        // TODO add your handling code here:
        clearall();
        autoid();
        autoidrecipe();
        tableload();
        tableloaddrug();
        btnInsert.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnRefreshDrugActionPerformed

    private void btnSearchDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDrugActionPerformed
        //Search Drug
        if(cbDrug.getSelectedItem().toString().equals("DrugName")){
            try {
                
            } catch (Exception e) {
                System.out.println("Error: " + e);
            }
        }else if(cbDrug.getSelectedItem().toString().equals("ID Drug")){
            try {
                
            } catch (Exception e) {
                System.out.println("Error: " + e);
            }
        }
    }//GEN-LAST:event_btnSearchDrugActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        //Search Recipe
        if(cdSearch.getSelectedItem().toString().equals("ID Recipe")){
            try {
                
            } catch (Exception e) {
                System.out.println("Error: " + e);
            }
        }else if(cdSearch.getSelectedItem().toString().equals("ID Drug")){            
            try {
                
            } catch (Exception e) {
                System.out.println("Error: " + e);
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    public void tableload(){
        try {
            
        } catch (Exception ex) {
            System.out.println("Error: " + ex);
        }
        
    }
    
    public void tableloaddrug(){
        try {
            
        } catch (Exception ex) {
            System.out.println("Error: " + ex);
        }
        
    }
    
    public void autoid(){
        try {
            
        }catch (Exception e) {
            System.out.println("Error: " + e);
        }
    }
    
    public void clearall(){
        txtIDR.setText("");
        txtIDD.setText("");
        txtQty.setText("0");
        txtDose.setText("");
        txtSub.setText("");
    }
    
    public void autoidrecipe(){
        try {
            
        } catch (Exception e) {
            System.out.println("Error: " + e);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRefreshDrug;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchDrug;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cbDrug;
    private javax.swing.JComboBox cdSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDose;
    private javax.swing.JLabel lblIDD;
    private javax.swing.JLabel lblIDR;
    private javax.swing.JLabel lblIDRD;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblRecipeDetail;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSub;
    private javax.swing.JTable tbDrug;
    private javax.swing.JTable tblRecipeDetail;
    private javax.swing.JTextField txtDose;
    private javax.swing.JTextField txtIDD;
    private javax.swing.JTextField txtIDR;
    private javax.swing.JTextField txtIDRD;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearchDrug;
    private javax.swing.JTextField txtSub;
    // End of variables declaration//GEN-END:variables
}
