/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import object.InDrug;
/**
 *
 * @author dhadotid
 */
public class JFAdminDrug extends javax.swing.JFrame {

    InDrug inDrug;
    DefaultTableModel tableModel;
    String datenow = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime()); //to get date now
    /**
     * Creates new form JFAdminDrug
     */
    public JFAdminDrug() {
        super("Drug");
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        setResizable(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        try
        {
         Registry myRegistry = LocateRegistry.getRegistry("127.0.0.1",1097);
         inDrug = (InDrug) myRegistry.lookup("objdrug");
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null,"Error 1 :"+ e);
        }
        txtDrugName.requestFocus();
        autoid();
        tableload();
        txtIDD.setEnabled(false);
        dcExpDate.getDateEditor().setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDrug = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtIDD = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        txtDrugName = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        txtStock = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        txtPrice = new javax.swing.JTextField();
        cbDrugtype = new javax.swing.JComboBox();
        lblDrug = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        dcExpDate = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        lblDrugName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel2.setText("Drug Type");

        btnSearch.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel3.setText("Stock");

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel4.setText("ExpDate");

        tblDrug.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Drug", "Drug Name", "Drug Type", "Stock", "ExpDate", "Price"
            }
        ));
        tblDrug.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDrugMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDrug);

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel5.setText("Price");

        txtIDD.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N

        btnInsert.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        txtDrugName.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N

        btnUpdate.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtStock.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N

        btnDelete.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtPrice.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N

        cbDrugtype.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        cbDrugtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tablet", "Capsule", "Syrup" }));

        lblDrug.setFont(new java.awt.Font("Californian FB", 1, 36)); // NOI18N
        lblDrug.setText("Drug");

        lblSearch.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        lblSearch.setText("Search");

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel1.setText("ID Drug");

        txtSearch.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N

        lblDrugName.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        lblDrugName.setText("Drug Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblDrugName)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDelete))
                            .addComponent(txtDrugName)
                            .addComponent(txtStock)
                            .addComponent(txtPrice)
                            .addComponent(btnInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtIDD, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbDrugtype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dcExpDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblSearch)
                                .addGap(144, 144, 144)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearch))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDrug)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDrug)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearch)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDrugName)
                            .addComponent(txtDrugName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cbDrugtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dcExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete)
                            .addComponent(btnUpdate)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        //Search Drug
        tableModel = (DefaultTableModel)tblDrug.getModel();
        tableModel.setRowCount(0);
        try {
            //inSpecialist.setSpcFare(Double.parseDouble(txtSearch.getText()));
            
            ArrayList data = inDrug.getRecord(txtSearch.getText());
            for(int i = 0;i < data.size()-1;i+=6)
            {
                //fac_code, fac_name, fac_email, fac_phone
                String idDrug = (String)data.get(i);
                String drugName = (String)data.get(i+1);
                String drugType = (String)data.get(i+2);
                int stock = (int)data.get(i+3);
                String expDate = (String)data.get(i+4);
                double price = (Double)data.get(i+5);
                String[] data_field = {idDrug.trim(),drugName.trim(),drugType.trim(), stock+"", expDate.trim(), price+ ""};
                tableModel.addRow(data_field);
            }
        } catch (Exception ex) {
            System.out.println("Error: " + ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        String exp = new SimpleDateFormat("yyyy-MM-dd").format(dcExpDate.getDate());
        if (txtIDD.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill in Id Drug");
        }else if(txtDrugName.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill in Drug Name");
            txtDrugName.requestFocus();
        }else if(cbDrugtype.getSelectedItem().toString().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter a valid Drug Type");
            cbDrugtype.requestFocus();
        }else if(txtStock.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter a valid Stock");
        }else if(dcExpDate.equals("") || exp.compareTo(datenow) < 0){
            JOptionPane.showMessageDialog(null, "Please fill in data ExpDate correctly");
            dcExpDate.requestFocus();
            System.out.println("Input: " + exp);
            System.out.println("Datenow: " + datenow);
        }else if(txtPrice.getText().matches("^\\d+$") == false || txtPrice.getText().equals("") || txtPrice.getText().length() < 2){
            JOptionPane.showMessageDialog(null, "Inccorect format price");
        }else{
            if(txtIDD.getText().equals("full")){
                JOptionPane.showConfirmDialog(null, "Data Drug has been full");
            }try{
                inDrug.setDrugName(txtDrugName.getText());
                inDrug.setDrugType(cbDrugtype.getSelectedItem().toString());
                inDrug.setDrugStock(Integer.parseInt(txtStock.getText()));
                inDrug.setDrugEXP(exp);
                inDrug.setDrugPrice(Double.parseDouble(txtPrice.getText()));

                int i = inDrug.doInsert();
                if(i != 0){
                    JOptionPane.showMessageDialog(null, "Data drug successful inputted");
                    autoid();
                    tableload();
                    txtPrice.setText("");
                    txtDrugName.setText("");
                }else{
                    JOptionPane.showMessageDialog(null, "Data drug failed inputted");
                }
            } catch (Exception e) {
                System.out.println("Error: " + e);
            }
        }

    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        //Update
        String gender = "";
        String exp = new SimpleDateFormat("yyyy-MM-dd").format(dcExpDate.getDate()); //get date now
        String expcompare = new SimpleDateFormat("yyyy").format(dcExpDate.getDate()); //get year

        try {
            
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure want to Update?" + txtDrugName.getText(), "Update", dialogButton);
                if(dialogResult == JOptionPane.YES_OPTION){
                    if(exp.equals("")){
                        JOptionPane.showMessageDialog(null, "Please enter the ExpDate");
                    }else if(txtDrugName.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "Please enter the Drug Name");
                    }else if(cbDrugtype.getSelectedItem().toString().equals("")){
                        JOptionPane.showMessageDialog(null, "Please enter a valid Drug Type");
                        cbDrugtype.requestFocus();
                    }else if(txtStock.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "Please enter a valid Stock");
                    }else if(dcExpDate.equals("") || datenow.compareTo(exp) > 0){
                        JOptionPane.showMessageDialog(null, "Please fill in data ExpDate correctly");
                        dcExpDate.requestFocus();
                        System.out.println("Input: " + exp);
                        System.out.println("Datenow: " + datenow);
                    }else if(txtPrice.getText().matches("^\\d+$") == false || txtPrice.getText().equals("") || txtPrice.getText().length() < 2){
                        JOptionPane.showMessageDialog(null, "Inccorect format price");
                    }else{
                        inDrug.setDrugID(txtIDD.getText());
                        inDrug.setDrugName(txtDrugName.getText());
                        inDrug.setDrugType(cbDrugtype.getSelectedItem().toString());
                        inDrug.setDrugStock(Integer.parseInt(txtStock.getText()));
                        inDrug.setDrugEXP(exp);
                        inDrug.setDrugPrice(Double.parseDouble(txtPrice.getText()));
                        int i = inDrug.doUpdate();
                        if(i != 0){
                            JOptionPane.showMessageDialog(null, "Data Drug successful updated");
                            tableload();
                            clearall();
                            autoid();
                        }else{
                            JOptionPane.showMessageDialog(null, "Data Drug failed updated");
                        }
                    }
                }
            
        } catch (Exception ex) {
            System.out.println("Error: " + ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        //delete
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure want to Delete?" + txtDrugName.getText(), "Delete", dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            try {
                inDrug.setDrugID(txtIDD.getText());
                int res = inDrug.doDelete();
                if(res > 0){
                    JOptionPane.showMessageDialog(null, "Success delete data " + txtDrugName.getText());
                    tableload();
                    clearall();
                    autoid();
                }
            } catch (Exception e) {
                System.out.println("Error: " + e);
            }
        }
        }

    public void autoid(){
        try {
            txtIDD.setText(inDrug.autoid());
        } catch (Exception e) {
            System.out.println("Error: " + e);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblDrugMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDrugMouseClicked
        //Mouse Click
        DefaultTableModel model = (DefaultTableModel)tblDrug.getModel();
        int selectedRowIndex = tblDrug.getSelectedRow();
        
        txtIDD.setText(model.getValueAt(selectedRowIndex, 0).toString());
        txtDrugName.setText(model.getValueAt(selectedRowIndex, 1).toString());
        cbDrugtype.setSelectedItem(model.getValueAt(selectedRowIndex, 2).toString());
        double stck = 0;
        stck = Double.parseDouble(model.getValueAt(selectedRowIndex, 3).toString());
        txtStock.setText(String.valueOf(stck));
        String date1 = "";
        date1 = (model.getValueAt(selectedRowIndex, 4).toString());
        java.util.Date date;
        try {
            date = new SimpleDateFormat("yyyy-MM-dd").parse(date1);
            dcExpDate.setDate(date);
        } catch (ParseException ex) {
            System.out.println("Error: " + ex);
        }
        double prc = 0;
        prc = Double.parseDouble(model.getValueAt(selectedRowIndex, 5).toString());
        txtPrice.setText(String.valueOf(prc));
        btnInsert.setEnabled(false);
        btnDelete.setEnabled(true);
        btnUpdate.setEnabled(true);
    }//GEN-LAST:event_tblDrugMouseClicked

    public void tableload(){
        tableModel = (DefaultTableModel)tblDrug.getModel();
        tableModel.setRowCount(0);
        try {
            ArrayList data = inDrug.tableDrug();
            for(int i = 0;i < data.size()-1;i+=6)
            {
                String idDrug = (String)data.get(i);
                String DrugName = (String)data.get(i+1);
                String DrugType = (String)data.get(i+2);
                int stock = (int)data.get(i+3);
                String ExpDate = (String)data.get(i+4);
                double price = (double)data.get(i+5);

                String[] data_field = {idDrug.trim(), DrugName.trim(),DrugType.trim(),stock +"", ExpDate.trim(), price+""};
                tableModel.addRow(data_field);
            }
        } catch (Exception ex) {
            System.out.println("Error: " + ex);
        }
        
    }

    public void clearall(){
        txtDrugName.setText("");
        cbDrugtype.getSelectedItem();
        txtStock.setText("");
        dcExpDate.setDate(null);
        txtPrice.setText("");
        txtSearch.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cbDrugtype;
    private com.toedter.calendar.JDateChooser dcExpDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDrug;
    private javax.swing.JLabel lblDrugName;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JTable tblDrug;
    private javax.swing.JTextField txtDrugName;
    private javax.swing.JTextField txtIDD;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
