/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.glass.events.KeyEvent;
import helper.LoginHelper;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import object.InLogin;

/**
 *
 * @author dhadotid
 */
public class JFMainMenu extends javax.swing.JFrame {
    InLogin iLogin;
    /**
     * Creates new form JFMainMenu
     */
    public JFMainMenu() {
        super("Main Menu");
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        setResizable(false);
        //setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        
        try
        {
         Registry myRegistry = LocateRegistry.getRegistry("127.0.0.1",1097);
         iLogin = (InLogin) myRegistry.lookup("objlogin");
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null,"Error 1 :"+ e);
        }
        
        JMWelcome.setEnabled(false);
        JMWelcome.setVisible(false);
        LoginPanel.setVisible(false);
        btnDoctor.setEnabled(false);
        btnPatient.setEnabled(false);
        btnTreatment.setEnabled(false);
        btnRecipe.setEnabled(false);
        btnPayment.setEnabled(false);
        btnDrug.setEnabled(false);
        btnSpecialist.setEnabled(false);
        btnUser.setEnabled(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pbIcon = new javax.swing.JLabel();
        lblYuhen = new javax.swing.JLabel();
        lblClinic = new javax.swing.JLabel();
        PanelMenu = new javax.swing.JPanel();
        LoginPanel = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnCancle = new javax.swing.JButton();
        btnDoctor = new javax.swing.JButton();
        btnPatient = new javax.swing.JButton();
        btnTreatment = new javax.swing.JButton();
        btnRecipe = new javax.swing.JButton();
        btnPayment = new javax.swing.JButton();
        btnDrug = new javax.swing.JButton();
        btnSpecialist = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMProgram = new javax.swing.JMenu();
        JMILogin = new javax.swing.JMenuItem();
        JMIAbout = new javax.swing.JMenuItem();
        JMWelcome = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pbIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Clinic_Entrance_change_1.png"))); // NOI18N

        lblYuhen.setFont(new java.awt.Font("Californian FB", 1, 36)); // NOI18N
        lblYuhen.setForeground(new java.awt.Color(0, 0, 0));
        lblYuhen.setText("Double R");

        lblClinic.setFont(new java.awt.Font("Californian FB", 1, 48)); // NOI18N
        lblClinic.setForeground(new java.awt.Color(51, 51, 51));
        lblClinic.setText("Clinic");

        LoginPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, ".: Please Login :.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Fax", 1, 14))); // NOI18N

        lblUsername.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        lblUsername.setText("Username");

        txtUsername.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        lblPassword.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        lblPassword.setText("Password");

        txtPassword.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnCancle.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        btnCancle.setText("Cancel");
        btnCancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addComponent(lblUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                        .addComponent(lblPassword)
                        .addGap(9, 9, 9)
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addComponent(btnLogin)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancle))
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnCancle))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnDoctor.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        btnDoctor.setText("Doctor");
        btnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorActionPerformed(evt);
            }
        });

        btnPatient.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        btnPatient.setText("Patient");
        btnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientActionPerformed(evt);
            }
        });

        btnTreatment.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        btnTreatment.setText("Treatment");
        btnTreatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTreatmentActionPerformed(evt);
            }
        });

        btnRecipe.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        btnRecipe.setText("Recipe");
        btnRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecipeActionPerformed(evt);
            }
        });

        btnPayment.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        btnPayment.setText("Payment");
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });

        btnDrug.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        btnDrug.setText("Drug");
        btnDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrugActionPerformed(evt);
            }
        });

        btnSpecialist.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        btnSpecialist.setText("Specialist");
        btnSpecialist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpecialistActionPerformed(evt);
            }
        });

        btnUser.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        btnUser.setText("User");
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });

        JMProgram.setText("Program");
        JMProgram.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N

        JMILogin.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        JMILogin.setText("Login");
        JMILogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMILoginActionPerformed(evt);
            }
        });
        JMProgram.add(JMILogin);

        JMIAbout.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        JMIAbout.setText("About");
        JMIAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIAboutActionPerformed(evt);
            }
        });
        JMProgram.add(JMIAbout);

        jMenuBar1.add(JMProgram);

        JMWelcome.setText("Welcome");
        JMWelcome.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jMenuBar1.add(JMWelcome);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblYuhen)
                            .addComponent(lblClinic)))
                    .addComponent(btnDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTreatment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRecipe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDrug, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSpecialist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblYuhen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblClinic))
                            .addComponent(pbIcon))
                        .addGap(41, 41, 41)
                        .addComponent(btnDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRecipe, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDrug, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSpecialist, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUser, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMILoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMILoginActionPerformed
        //Button Login and Logout
        if(JMILogin.getText().trim().equals("Logout")){
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure want to logout?", "Logout", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {
                
                JMWelcome.setEnabled(false);
                JMWelcome.setVisible(false);
                btnDoctor.setEnabled(false);
                btnPatient.setEnabled(false);
                btnTreatment.setEnabled(false);
                btnRecipe.setEnabled(false);
                btnPayment.setEnabled(false);
                btnDrug.setEnabled(false);
                btnUser.setEnabled(false);
                btnSpecialist.setEnabled(false);
                JMILogin.setText("Login");
                LoginPanel.setVisible(false);
            }
            
        }else if(JMILogin.getText().trim().equals("Login")){
            LoginPanel.setVisible(true);
            txtUsername.requestFocus();
            //txtUsername.grabFocus();
        }
    }//GEN-LAST:event_JMILoginActionPerformed

    private void btnCancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancleActionPerformed
        //Button Cancle in Panel Login
        txtUsername.setText(null);
        txtPassword.setText(null);
        LoginPanel.setVisible(false);
    }//GEN-LAST:event_btnCancleActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        //Button Login in Panel Login and check access level
        if(txtUsername.getText() == null){
            JOptionPane.showMessageDialog(null, "Please fill in Username");
        }else if(txtPassword.getText() == null){
            JOptionPane.showMessageDialog(null, "Please fill in Password");
        }else{
            try {
                //disini buat loginnya
                iLogin.setUsername(txtUsername.getText());
                iLogin.setPassword(txtPassword.getText());
                
                int cek = iLogin.doLogin();//rs.getInt("hasil");
                if(cek > 0){
                    String[] data = iLogin.cekAccess();
                    LoginHelper.idUser = data[0];
                    LoginHelper.uName = data[1];
                    LoginHelper.isAdmin = data[2];
                    if(LoginHelper.isAdmin.equals("1")){
                        JOptionPane.showMessageDialog(null, "Welcome, " + txtUsername.getText() + ". \n Have a nice day:)");
                        btnDoctor.setEnabled(true);
                        btnPatient.setEnabled(true);
                        btnTreatment.setEnabled(true);
                        btnRecipe.setEnabled(true);
                        btnPayment.setEnabled(true);
                        btnDrug.setEnabled(true);
                        btnSpecialist.setEnabled(true);
                        btnUser.setEnabled(true);
                        JMWelcome.setVisible(true);
                        JMWelcome.setText("Welcome: " + txtUsername.getText());
                        JMILogin.setText("Logout");
                        LoginPanel.setVisible(false);
                        txtUsername.setText(null);
                        txtPassword.setText(null);                      
                        
                    }else if(LoginHelper.isAdmin.equals("0")){
                        JOptionPane.showMessageDialog(null, "Welcome, " + txtUsername.getText() + ". \n Have a nice day:)");
                        btnDoctor.setEnabled(false);
                        btnPatient.setEnabled(true);
                        btnTreatment.setEnabled(true);
                        btnRecipe.setEnabled(true);
                        btnPayment.setEnabled(true);
                        btnDrug.setEnabled(false);
                        btnSpecialist.setEnabled(false);
                        btnUser.setEnabled(false);
                        JMWelcome.setVisible(true);
                        JMWelcome.setText("Welcome: " + txtUsername.getText());
                        JMILogin.setText("Logout");
                        LoginPanel.setVisible(false);
                        txtUsername.setText(null);
                        txtPassword.setText(null);
                    }
                }else if((cek == 0)){
                    JOptionPane.showMessageDialog(null, "Incorrect username or password or login level not accordance.");
                    JMWelcome.setEnabled(false);
                    JMWelcome.setVisible(false);
                    JMILogin.setText("Login");
                }
            } catch (Exception e) {
                System.out.println("Error " + e);
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        //Enter in textbox password for click button login
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnLogin.doClick();
        }
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void btnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorActionPerformed
        //button doctor for open windows form doctor just for admin
        if (LoginHelper.isAdmin.equals("1")) {
            JFAdminDoctor JFDA = new JFAdminDoctor();
            JFDA.setVisible(true);
        }
    }//GEN-LAST:event_btnDoctorActionPerformed

    private void btnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientActionPerformed
        //button patient for open window form patient and check the access level login
        if(LoginHelper.isAdmin.equals("1")){
            JFAdminPatient JAFP = new JFAdminPatient();
            JAFP.setVisible(true);
        }else if(LoginHelper.isAdmin.equals("0")){
            JFAdminPatient JAFP = new JFAdminPatient();
            JAFP.setVisible(true);
        }
    }//GEN-LAST:event_btnPatientActionPerformed

    private void btnSpecialistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpecialistActionPerformed
        //button Specialist for open window form specialist and check the access level login
        if(LoginHelper.isAdmin.equals("1")){
            JFAdminSpecialist jafs = new JFAdminSpecialist();
            jafs.setVisible(true);
        }
    }//GEN-LAST:event_btnSpecialistActionPerformed

    private void btnTreatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreatmentActionPerformed
        //button treatment for open window form treatment and check the access level login
        if(LoginHelper.isAdmin.equals("1")){
            JFUserTreatment jfut = new JFUserTreatment();
            jfut.setVisible(true);
        }else if(LoginHelper.isAdmin.equals("0")){
            JFUserTreatment jfut = new JFUserTreatment();
            jfut.setVisible(true);
        }
    }//GEN-LAST:event_btnTreatmentActionPerformed

    private void btnRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecipeActionPerformed
        //button recipe for open window form recipe and check the access level login
        if(LoginHelper.isAdmin.equals("0")){
            JFUserRecipeDetail jfurd = new JFUserRecipeDetail();
            jfurd.setVisible(true);
        }else if(LoginHelper.isAdmin.equals("1")){
            JFUserRecipeDetail jfurd = new JFUserRecipeDetail();
            jfurd.setVisible(true);
        }
    }//GEN-LAST:event_btnRecipeActionPerformed

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        //button payment for open window form payment and check the access level login
        if(LoginHelper.isAdmin.equals("0")){
            JFUserPayment jfup = new JFUserPayment();
            jfup.setVisible(true);
        }else if(LoginHelper.isAdmin.equals("1")){
            JFUserPayment jfup = new JFUserPayment();
            jfup.setVisible(true);
        }
    }//GEN-LAST:event_btnPaymentActionPerformed

    private void btnDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrugActionPerformed
        // TODO add your handling code here:
        if(LoginHelper.isAdmin.equals("1")){
            JFAdminDrug jafd = new JFAdminDrug();
            jafd.setVisible(true);
        }
    }//GEN-LAST:event_btnDrugActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
        if (LoginHelper.isAdmin.equals("1")) {
            JFAdminUser jfau = new JFAdminUser();
            jfau.setVisible(true);
        }
    }//GEN-LAST:event_btnUserActionPerformed

    private void JMIAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIAboutActionPerformed
        //About
        JOptionPane.showMessageDialog(null, "This project is created by: \n Raden Satria Yudha Purbajagad\nGarin Ramadhan\n\nFollow my instagram: yudhapurbajagad");
    }//GEN-LAST:event_JMIAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                    UIManager.setLookAndFeel("com.jtattoo.plaf.bernstein.BernsteinLookAndFeel");
                    SwingUtilities.updateComponentTreeUI(new JFMainMenu());
                }catch(Exception e){
                    
                }
//                JFMainMenu.setUndecorated(true);
//                JFMainMenu.getRootPane().setWindowDecorationStyle(HIDE_ON_CLOSE);
                new JFMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMIAbout;
    private javax.swing.JMenuItem JMILogin;
    private javax.swing.JMenu JMProgram;
    private javax.swing.JMenu JMWelcome;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JButton btnCancle;
    private javax.swing.JButton btnDoctor;
    private javax.swing.JButton btnDrug;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnPatient;
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton btnRecipe;
    private javax.swing.JButton btnSpecialist;
    private javax.swing.JButton btnTreatment;
    private javax.swing.JButton btnUser;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblClinic;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblYuhen;
    private javax.swing.JLabel pbIcon;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
