/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import object.InPayment;

/**
 *
 * @author dhadotid
 */
public class JFUserPayment extends javax.swing.JFrame {

    InPayment inPayment;
    DefaultTableModel tableModel;
    double totpay = 0;
    double cash = 0;
    double change = 0;
    /**
     * Creates new form JFUserPayment
     */
    public JFUserPayment() {
        super("Payment");
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        setResizable(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        txtCash.requestFocus();
        txtIdPayment.setEnabled(false);
        txtPatientName.setEnabled(false);
        txtPaymentDoc.setEnabled(false);
        txtDiagnose.setEnabled(false);
        txtPaymentDrug.setEnabled(false);
        txtTotalPay.setEnabled(false);
        txtChange.setEnabled(false);
        jButton2.setEnabled(false);
        
        try
        {
         Registry myRegistry = LocateRegistry.getRegistry("127.0.0.1",1097);
         inPayment = (InPayment) myRegistry.lookup("objpayment");
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null,"Error 1 :"+ e);
        }
        
        autoid();
        paymentIsNotyetPay();
        onCloseClicked();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdPayment = new javax.swing.JTextField();
        txtPatientName = new javax.swing.JTextField();
        txtDiagnose = new javax.swing.JTextField();
        txtPaymentDrug = new javax.swing.JTextField();
        txtTotalPay = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCash = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtChange = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDT = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPay = new javax.swing.JTable();
        txtPaymentDoc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnPayHis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 0, 24)); // NOI18N
        jLabel1.setText("Payment");

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel2.setText("Id Payment");

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel3.setText("Patient Name");

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel4.setText("Payment Doctor");

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel5.setText("Payment Drug");

        jLabel6.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel6.setText("Total Payment");

        txtIdPayment.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N

        txtPatientName.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N

        txtDiagnose.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N

        txtPaymentDrug.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N

        txtTotalPay.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel7.setText("Cash");

        txtCash.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel8.setText("Change");

        txtChange.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel9.setText("Detail Transaction");

        tbDT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Payment", "Patient Name", "Doctor Name", "Drug Name", "Price", "Qty", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tbDT);

        jButton1.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel10.setText("Search Transaction");

        txtSearch.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N

        btnSearch.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tbPay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Payment", "Patient Name", "Diagnose", "Payment Doctor", "Payment Drug", "Total Payment"
            }
        ));
        tbPay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPayMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbPay);

        txtPaymentDoc.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel11.setText("Diagnose");

        jButton2.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnPayHis.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        btnPayHis.setText("Payment History");
        btnPayHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayHisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(58, 58, 58))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdPayment, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(txtPatientName)
                                    .addComponent(txtDiagnose, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPaymentDrug)
                                    .addComponent(txtTotalPay)
                                    .addComponent(txtCash)
                                    .addComponent(txtPaymentDoc, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                                .addComponent(txtChange, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnPayHis)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(btnSearch)
                                .addGap(115, 115, 115)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiagnose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPaymentDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPaymentDrug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btnSearch)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPayHis))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cash = Double.parseDouble(txtCash.getText());
        System.out.println("Cash " + cash + " totpay " + totpay);
        if(txtPatientName.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please select patient from below table");
        }else if(cash < totpay){
            JOptionPane.showMessageDialog(null, "Your change is less than total payment");
        }else if(txtCash.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter cash");
        }else{
            change = cash - totpay;
            String strchange = "";
            strchange = String.valueOf(change);
            txtChange.setText(strchange);
            JOptionPane.showMessageDialog(null, "Total Payment is " + totpay + ". and your money is " + cash + ". \nyour change is " + change);
            jButton2.setEnabled(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        tableModel = (DefaultTableModel)tbPay.getModel();
        tableModel.setRowCount(0);
        try {
            //inSpecialist.setSpcFare(Double.parseDouble(txtSearch.getText()));
            
            ArrayList data = inPayment.getRecordDetailPayment(txtSearch.getText());
            for(int i = 0;i < data.size()-1;i+=8)
            {
                //fac_code, fac_name, fac_email, fac_phone
                String idPay = (String)data.get(i);
                String patientName = (String)data.get(i+1);
                String doctorName = (String)data.get(i+2);
                String diagnose = (String)data.get(i+3);
                String datetreat = (String)data.get(i+4);
                double payDoc = (double)data.get(i+5);
                double payDrug = (double)data.get(i+6);
                double totalPay = (double)data.get(i+7);
                String[] data_field = {idPay.trim(),patientName.trim(),doctorName.trim(),diagnose.trim(),datetreat.trim(),payDoc+"",payDrug+"",totalPay+""};
                tableModel.addRow(data_field);
            }
        } catch (Exception ex) {
            System.out.println("Error: " + ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tbPayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPayMouseClicked
        DefaultTableModel model = (DefaultTableModel)tbPay.getModel();
        int selectedRowIndex = tbPay.getSelectedRow();
        
        txtIdPayment.setText(model.getValueAt(selectedRowIndex, 0).toString());
        txtPatientName.setText(model.getValueAt(selectedRowIndex, 1).toString());
        txtDiagnose.setText(model.getValueAt(selectedRowIndex, 2).toString());
        txtPaymentDoc.setText(model.getValueAt(selectedRowIndex, 3).toString());
        txtPaymentDrug.setText(model.getValueAt(selectedRowIndex, 4).toString());
        txtTotalPay.setText(model.getValueAt(selectedRowIndex, 5).toString());
        
        totpay = Double.parseDouble(txtTotalPay.getText());
        
        tabledetails(txtIdPayment.getText());
        jButton2.setEnabled(false);
    }//GEN-LAST:event_tbPayMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            inPayment.setPayID(txtIdPayment.getText());
            int i = inPayment.doUpdate();
            if(i != 0){
                JOptionPane.showMessageDialog(null, "Success saved transaction record");
                autoid();
                txtPatientName.setText("");
                txtDiagnose.setText("");
                txtPaymentDoc.setText("");
                txtPaymentDrug.setText("");
                txtTotalPay.setText("");
                txtCash.setText("");
                txtChange.setText("");
                paymentIsNotyetPay();
                tableModel = (DefaultTableModel)tbDT.getModel();
                tableModel.setRowCount(0);
                jButton2.setEnabled(false);
            }else{
                JOptionPane.showMessageDialog(null, "Failed save record transaction");
            }
        } catch (Exception ex) {
            System.out.println("Error: " + ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnPayHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayHisActionPerformed
        JFPaymentHistory ph = new JFPaymentHistory();
        ph.show();
    }//GEN-LAST:event_btnPayHisActionPerformed

    private void onCloseClicked(){
        this.setDefaultCloseOperation(JFUserRecipeDetail.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowListener() {

            @Override
            public void windowOpened(WindowEvent e) {
                
            }

            @Override
            public void windowClosing(WindowEvent e) {
                String objButton[] = {"Yes","No"};
                if(!txtPatientName.getText().equals("")){
                    int PromptResult = JOptionPane.showOptionDialog(null, "Are you sure want to back?\nYou are not save this record yet!","Double R Clinic", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, objButton, objButton[1]);
                    if (PromptResult == JOptionPane.YES_OPTION) {
                        dispose();
                    }
                }else{
                    dispose();
                }
            }

            @Override
            public void windowClosed(WindowEvent e) {
                
            }

            @Override
            public void windowIconified(WindowEvent e) {
                
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
                
            }

            @Override
            public void windowActivated(WindowEvent e) {
                
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
                
            }
        });
    }
    private void tabledetails(String idPayment){
        tableModel = (DefaultTableModel)tbDT.getModel();
        tableModel.setRowCount(0);
        try {
            ArrayList data = inPayment.getRecordDetailPayment(idPayment);
            for(int i = 0;i < data.size()-1;i+=7)
            {
                String idPay = (String)data.get(i);
                String PatientName = (String)data.get(i+1);
                String DoctorName = (String)data.get(i+2);
                String DrugName = (String)data.get(i+3);
                double price = (double)data.get(i+4);
                int qty = (int)data.get(i+5);
                double subtotal = (double)data.get(i+6);

                String[] data_field = {idPay.trim(), PatientName.trim(),DoctorName.trim(),DrugName.trim(),price+"",qty+"", subtotal+""};
                tableModel.addRow(data_field);
            }
        } catch (Exception ex) {
            System.out.println("Error: " + ex);
        }
    }
    
    private void paymentIsNotyetPay(){
        tableModel = (DefaultTableModel)tbPay.getModel();
        tableModel.setRowCount(0);
        try {
            ArrayList data = inPayment.tablePayment();
            for(int i = 0;i < data.size()-1;i+=6)
            {
                String idPay = (String)data.get(i);
                String PatientName = (String)data.get(i+1);
                String Diagnose = (String)data.get(i+2);
                double payDoc = (double)data.get(i+3);
                double payDrug = (double)data.get(i+4);
                double totPay = (double)data.get(i+5);

                String[] data_field = {idPay.trim(), PatientName.trim(),Diagnose.trim(),payDoc+"",payDrug+"", totPay+""};
                tableModel.addRow(data_field);
            }
        } catch (Exception ex) {
            System.out.println("Error Disini: " + ex);
        }
    }
    
    private void autoid(){
        try {
            txtIdPayment.setText(inPayment.autoid());
        } catch (Exception ex) {
            System.out.println("Error Autoid: " + ex);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPayHis;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbDT;
    private javax.swing.JTable tbPay;
    private javax.swing.JTextField txtCash;
    private javax.swing.JTextField txtChange;
    private javax.swing.JTextField txtDiagnose;
    private javax.swing.JTextField txtIdPayment;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtPaymentDoc;
    private javax.swing.JTextField txtPaymentDrug;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTotalPay;
    // End of variables declaration//GEN-END:variables
}
